### ISSUE TITLE
Window doesnt look like in figma

### ISSUE THREAD

**Issue by Vinyzu** [ParthJadhav/Tkinter-Designer#105]
figma link:
https://www.figma.com/file/SmMH601IW47DIQ8RsyiMZQ/Untitled?node-id=0%3A1
In the picture: left is figma (how it should look like), right is the app
![fnjwenf](https://user-images.githubusercontent.com/50874994/127522804-5e4f5d2b-1fa1-46d4-8841-dc541761c11b.PNG)

**Comment by ParthJadhav** [comment]
1. Remove the text from the "Image" Group.
2. Change the name "Background" to "Image"
3. Button will have the white area around it because Tkinter does not process transparent images correctly. To get rid of it you need to have the image part as the background of the button. You can do this by duplicating the image and then cropping it to fit the part of the button.

**Comment by Vinyzu** [comment]
Ok, thanks for the quick answer, but for point 3, i dont know how to crop a image without "cropping" it else than this mask tool, which isnt working...

**Comment by ParthJadhav** [comment]
can you give me edit permissions to the file ?

**Comment by Vinyzu** [comment]
You should have it now!

**Comment by Vinyzu** [comment]
Ok i kinda get it im just at my phone rn so its just a mess

**Comment by ParthJadhav** [comment]
LOL, you should've told me before

**Comment by Vinyzu** [comment]
Hahaha sry 😬😬😬😬

**Comment by ParthJadhav** [comment]
https://github.com/ParthJadhav/Tkinter-Designer/blob/master/docs/instructions.md

**Comment by Vinyzu** [comment]
Ok thanks! Ill try it tmrw!
