### ISSUE TITLE
when I follow the instructions, it raise exceptions as follows

### ISSUE THREAD

**Issue by somenzz** [ParthJadhav/Tkinter-Designer#28]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 1883, in __call__
    return self.func(*args)
  File "tkinter_designer.py", line 29, in btn_clicked
    backend.generate_code(token,URL, output_path)
  File "/Users/aaron/tmp/Tkinter-Designer/backend.py", line 142, in generate_code
    window_elements = fig_window["children"]
KeyError: 'children'

**Comment by ParthJadhav** [comment]
Thanks for creating an Issue, We will be eager to solve it.

**Comment by ParthJadhav** [comment]
Can I see the Figma file ?

**Comment by somenzz** [comment]
https://www.figma.com/file/S4eqQX6wjUQ0rrNUTsHmqk/Figma-iOS-UI-Kit-Free-Community?node-id=52%3A0

**Comment by ParthJadhav** [comment]
Or just send the screenshot of the layers panel on the left.

**Comment by ParthJadhav** [comment]
Ohh, you are using a UI kit which has multiple elements some being outside the frame.

If a text is outside a frame it would consider tkinter designer as a frame and will try to see into its children's . But since it doesn't have any it would give an error.


Create a new file and in it only create a single frame and put all your design into it. Also keep in mind the naming.  

Read instructions or watch the video.

**Comment by somenzz** [comment]
Thank you very much
