### ISSUE TITLE
[TRANSLATION] Added Translation for Gujarati Language

### ISSUE THREAD

**Issue by Dev-Mehta** [ParthJadhav/Tkinter-Designer#57]
@ParthJadhav please review the gujarati translation and merge it. See pull request #56

**Comment by ParthJadhav** [comment]
Thanks for creating an issue, we are eager to solve it.

**Comment by ParthJadhav** [comment]
Thanks @Dev-Mehta for the translation ! reviewing it...

**Comment by piccoloser** [comment]
I commented on the PR, seems to need some work before it'll be ready to merge.

Currently, the HTML is broken because it got run through the translator, the filenames use a different standard than the project as a whole, and changing the translations list to a dropdown will probably be unnecessary, given the short list of languages currently available.

**Comment by Dev-Mehta** [comment]
@ParthJadhav @piccoloser Kindly check the updated code

**Comment by piccoloser** [comment]
@Dev-Mehta The updated files look good to go!

**Comment by piccoloser** [comment]
As an aside, I'm not sure if the keys (for shortcuts) would change at all.

**Comment by Dev-Mehta** [comment]
> As an aside, I'm not sure if the keys (for shortcuts) would change at all. This might apply to other translations as well, but then again I could be wrong.

No they won't change as it depends on the keyboard layout of the PC.

**Comment by piccoloser** [comment]
I see, thanks for clarifying!
