### ISSUE TITLE
Fonts not working properly

### ISSUE THREAD

**Issue by Pigii** [ParthJadhav/Tkinter-Designer#76]
When I try to create a text with a font on Figma it changes it when it gets exported.
this is the Figma project:
![image](https://user-images.githubusercontent.com/54852275/125993914-35531194-38c5-4b9d-92cb-de7153cae26f.png)

And this is the result:
![image](https://user-images.githubusercontent.com/54852275/125993960-43222845-de27-45d8-b6c6-9da3d0edb334.png)

Note that this happens with every font, not only this one

**Comment by ParthJadhav** [comment]
The font you select on the Figma website must be installed on your machine. Check if your selected font is installed on your device.

**Comment by ParthJadhav** [comment]
Also https://github.com/ParthJadhav/Tkinter-Designer/issues/78

**Comment by Pigii** [comment]
> The font you select on the Figma website must be installed on your machine. Check if your selected font is installed on your device.

If I try to use Roboto bold on Figma it will export as `font = ("Roboto-Bold")`. this will show up as some font that is not Roboto bold. if I change the `font = ("Roboto-Bold")` into `font = ("Roboto Bold")` it will show up as Roboto bold.

**Comment by ParthJadhav** [comment]
That's Strange because on my side it works perfectly fine ->

Roboto Medium -> Roboto Bold -> Roboto Light

Tkinter - 
<img width="534" alt="Screenshot 2021-07-17 at 5 25 50 PM" src="https://user-images.githubusercontent.com/42001064/126036055-de690667-127b-49ef-bb64-e5b74a820233.png">

Figma - 
![Screenshot 2021-07-17 at 5 26 40 PM](https://user-images.githubusercontent.com/42001064/126036076-53e9ec0e-c8bd-448c-af5f-53bef270df9a.png)

**Comment by ParthJadhav** [comment]
> What platform are you testing it on? Windows?

He is testing on windows. From the look of his status bar. Replied for your convenience.

**Comment by saur0x** [comment]
I added it in my PR #87 . Hopefully that will fix the font issues.

**Comment by ParthJadhav** [comment]
Hey @Pigii the problem has been resolved in the latest version.
