### ISSUE TITLE
Add package installation and usage to README and instructions

### ISSUE THREAD

**Issue by jrobchin** [ParthJadhav/Tkinter-Designer#98]
Just adding a quick issue as a reminder to add the PyPi installation and CLI usage instructions to the README and instructions docs since it's the easiest and quickest way for people to get started with this tool.

I'll make the changes when I get the chance unless someone beats me to it.

**Comment by ParthJadhav** [comment]
Yeah, once the ongoing changes are done; I'll be adding the instructions. 

> I'll make the changes when I get the chance unless someone beats me to it.

LOL 😂

**Comment by ParthJadhav** [comment]
Currently @jvendegna is working on CI CD for Building and Publishing the package to PYPI it will be done soon.

**Comment by ParthJadhav** [comment]
Hey 
@jrobchin 
@neilbaldwin 
@saur0x 

Sorry we had merged this PR https://github.com/ParthJadhav/Tkinter-Designer/pull/84 without any notice or comment. 

The changes are :- 

1. Every future PR would be checked for Linting and Syntax errors and warn you if it fails.
2. It will also perform some basic tests.
3. Before the PR is merged the contributor or maintainer would require to push a tag with a respective semantic version bump. 

    For E.g - If you had fixed some text issues in the PR and it is ready to merge then you need to push a tag with a bump in Z.
    `git tag -a X.Y.(Z + 1) -m "<Message>"`
    
    For E.g - If you have made some major changes in Naming then you need to push a tag with a bump in X. 
    ``git tag -a (X+1).Y.Z -m "<Message>"``
    
    X - Major Change
    Y - Minor Change
    Z - Patch or Fix

4. And when the PR is merged it would look for that latest tag and upload the package to PYPI with the version you specified.

I may not be 100% right so I would request @jvendegna to review the above steps and changes.

**Comment by ParthJadhav** [comment]
Hey @jrobchin , I also added the instructions to the PyPi package... Let me know if there are any changes, I haven't translated it yet.

https://github.com/ParthJadhav/Tkinter-Designer/blob/master/docs/instructions.md#using-the-cli

**Comment by jvendegna** [comment]
Sorry for the delay. 

Yeah, that's correct. I think of semver like: broke_everything.new_feature.bugfix

If the git tag flow is okay with everyone we can stick with it. If it's confusing or causing issues let me know. Always another way.

**Comment by jvendegna** [comment]
> Before the PR is merged the contributor or maintainer would require to push a tag with a respective semantic version bump.

I wanted to mention that you can tag commits after the fact and I am testing a way to ensure that if you push a tag to a commit on master a release job is triggered. So it shouldn't be a big deal if anyone forgets this step. But my opinion is that every commit to master should trigger a new release.

It also should be the contributor to tag the commit rather than anyone reviewing the PR or clicking the merge button. The tag should be a part of the forked PR coming into this repo.... I think. 🤔

**Comment by ParthJadhav** [comment]
> > Before the PR is merged the contributor or maintainer would require to push a tag with a respective semantic version bump.
> 
> I wanted to mention that you can tag commits after the fact and I am testing a way to ensure that if you push a tag to a commit on master a release job is triggered. So it shouldn't be a big deal if anyone forgets this step. But my opinion is that every commit to master should trigger a new release.

I guess a build should be triggered only when a tag is pushed. Because there are many commits which does not change the code or functionality of the code and creating a build for every small change is not needed. 

> It also should be the contributor to tag the commit rather than anyone reviewing the PR or clicking the merge button. The tag should be a part of the forked PR coming into this repo.... I think. 🤔

There could be many people like me who didn't know how to push a tag :) If we could use [Danger](https://danger.systems/python/)  to tell the user's if they have missed a tag (Only if they have changed the code not documentation) and how to create a tag. If that works then it would be awesome. IDK if it's possible, Just a guess ;)
